network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s31f6:
      dhcp4: false
      dhcp6: false
      addresses:
        - 192.168.0.50/24
      routes:
      - to: 0.0.0.0/0
        via: 192.168.0.1      
      nameservers:
        addresses:
          - 192.168.0.1
          - 8.8.8.8
