apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""        # Important for static binding
  hostPath:
    path: "/mnt/data/postgres"
  claimRef:
    namespace: default       # Adjust if not default namespace
    name: pgdata-postgres-0 # This must match the PVC created by StatefulSet